### ISSUE TITLE
MYSQL support ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [angel-dart/orm#30]
Hello everyone 

has anybody attempted building support for MySQL ?

**Comment by thosakwe** [comment]
AFAIK, the Dart MySQL driver isn’t compatible with Angel due to outdated
dependencies. Also, it’s unmaintained.

Eventually, I’ll change the way the ORM is written so that it can be used
with other databases, like MySQL, and potentially even NoSQL.

I’ll have time to really work once exams are done.

**Comment by sandrobilbeisi** [comment]
cool, thanks !
Good Luck with your exams !!!

**Comment by thosakwe** [comment]
Thanks! Gonna leave this issue open. I’m not much of a PostgreSQL fan,
honestly. The main reason I chose it was so that there would be a
comparable offering to the one Aqueduct has. However, Angel’s ORM doesn’t
necessarily require Angel, which is a benefit.

**Comment by thosakwe** [comment]
#35 will eventually lead to solution

**Comment by thosakwe** [comment]
I will mark this as closed, because I'm aiming for MySQL support in the upcoming 2.0 release.
