### ISSUE TITLE
Can angel_orm work with flutter?

### ISSUE THREAD

**Issue by Rockvole** [angel-dart/orm#44]
I notice you have recently changed orm to be "database agnostic". 
Would it be possible to use angel orm with sqlite in flutter ?

I am looking for a solution where I can have (mostly) the same database code in flutter (sqlite) and on the server side (preferably mysql).

**Comment by thosakwe** [comment]
ORM is currently aimed towards PostgreSQL; you'd have to write your own adapter for both SQLite and MySQL.

The stories for both SQLite and PostgreSQL are not that great in Dart yet, so I might not add support for a long time, if ever.

Also, the ORM is not database agnostic. Please link to where it says this, so that i can edit it. Things have changed in Angel 2.

*Services*, though, however are and always will be database-agnostic.
